### PR TITLE
Add enumerize and fix git

### PR DESCRIPTION
**Pull request by gmq**

### CODE REVIEW

**Comment by gmq** [comment]
[[2p/18v] enumerize debiera incluirse en el gemfile base de potassium](https://trello.com/c/6P51BC04/424-2p-18v-enumerize-debiera-incluirse-en-el-gemfile-base-de-potassium)

**Comment by gmq** [comment]
[[4p/18v] Potassium - Quedan cosas fuera del initial commit luego del create](https://trello.com/c/m1tHQmrQ/387-4p-18v-potassium-quedan-cosas-fuera-del-initial-commit-luego-del-create)

**Comment by blackjid** [comment]
😱  two features in the same PR!!!

**Comment by blackjid** [comment]
bakan!

**Comment by llekn** [comment]
@blackjid think about this as "two features for the price of one, yay!!"

**Pull request merged**
